name: PR Changelog Reminder

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'

jobs:
  test-run:
    name: A first test run

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@main
      - name: Wait for a second
        uses: ./
        with:
          milliseconds: 1000
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
